# https://alacritty.org/config-alacritty.html
# Alacritty configuration file
 
# https://alacritty.org/config-alacritty.html#window
[window]
opacity = 0.99
padding = { x = 8, y = 8 }
 
# https://alacritty.org/config-alacritty.html#terminal
[terminal]
shell = "bash"
 
[font]
normal = { family = "Iosevka", style="Regular"}
size = 11
 
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
 
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"
 
[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"
 
[cursor]
style = "Block"
unfocused_hollow = true
 
[env]
TERM = "xterm-256color"
